name: toasttab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  fluttertoast: ^9.0.0
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  pinput: ^6.0.2
  socket_io_client: ^3.1.4
  animate_do: ^4.2.0
  flutter_thermal_printer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/
    
  uses-material-design: true


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
