name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5' # or your version

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Archive Build
        run: |
          mkdir build_output
          xcopy build\windows\x64\runner\Release build_output /E /I

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build_output
